spring:
  application:
    name: word-provider
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orcaDB

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

server:
  port: 8091



