spring:
  application:
    name: language-provider
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orcaDB

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
server:
  port: ${PORT:8092}
