spring:
  application:
    name: language-service

server:
  port: 8888

language-provider:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090
    ServerListRefreshInterval: 15000
